name: List Deployments
on:
  workflow_dispatch:

jobs:
  list:
    uses: kanzalqalandri/platform-workflows/.github/workflows/list-tenants.yml@main
    with:
      plane: powergrader
      app: pwg-ui
    secrets: inherit
